### ISSUE TITLE
No link created in Twitter

### ISSUE THREAD

**Issue by supergia** [fourtonfish/SimpleSharingButtons#2]
Many people have told me the the code, if the subject is too long, does not produce a link to the page for Twitter.  Thanks.

**Comment by fourtonfish** [comment]
@supergia 

Hi -- and thanks for reporting this issue!

Can you describe exactly what you're trying to do? I tried submitting a very long text into the "Short title" field and the URL still appeared when I tried to share the page on Twitter.

[Here is the link](https://twitter.com/intent/tweet?source=http%3A%2F%2Fsimplesharingbuttons.com%2F&text=Loremipsumdolorsitamet%2Calteraevertimaiorumadcum%2Ceasedadhucpropriae%2Cpurtoeuismodnamei.Eripuitmentitumperpetuautvel%2Ccuseaoporteatmediocritatem.Veldictasplaceratpertinaciaet%2Cidipsumeirmodmelioremel%2Ceausuaequesalutatusvoluptatum.Nesitjustolibercausae.Utvelitlabiturdelicatissimiest%2Cexeamsinttacimates.Solutamaluisseturbanitasmeiex%2Clibrismuciusgraecohisin.:%20http%3A%2F%2Fsimplesharingbuttons.com%2F) (screenshot below).

![screen shot 2015-03-13 at 12 31 21 pm](https://cloud.githubusercontent.com/assets/3909390/6642681/e7d3a6c6-c97c-11e4-8414-bacd80fb27c7.png)

**Comment by supergia** [comment]
Hello Stefan,

My apologies.  I just looked at the three blasts I just did with Twitter sharing links and I realized that the HTML was not complete.  

What I started doing to add each on of my share links was instead of hard coding the html source, I was using Dreamweaver's properties link box and copying the link from your page and then pasting it into the properties box.  It was not getting it all.  Sorry about that and I will make another donation. 

Best wishes 

Marshall



 

 
On Mar 13, 2015, at 9:33 AM, Stefan Bohacek wrote:

@supergia

Hi -- and thanks for reporting this issue!

Can you describe exactly what you're trying to do? I tried submitting a very long text into the "Short title" field and the URL still appeared when I tried to share the page on Twitter.

Here is the link (screenshot below).

**Comment by fourtonfish** [comment]
Ah, got it -- no problem!

Thanks for the donation -- and thanks for using my website :-)
