### ISSUE TITLE
Facebook share URL doesn't seem right

### ISSUE THREAD

**Issue by nabsul** [fourtonfish/SimpleSharingButtons#23]
Facebook is asking for an "href" parameter in the share URL, I think in the place of the "u" param.

**Comment by fourtonfish** [comment]
Hi, could you share the full error and steps to reproduce it?

The URL [generated by the site](https://www.facebook.com/sharer/sharer.php?u=http%3A%2F%2Fsimplesharingbuttons.com%2F) seems to work fine, but [this one](https://www.facebook.com/sharer/sharer.php?href=http%3A%2F%2Fsimplesharingbuttons.com%2F) not.

**Comment by nabsul** [comment]
Strange! Only difference is that I was still testing it on localhost. Maybe that's the problem.

Let's close this for now, I'll reopen if it gives me trouble after testing with a real domain.

**Comment by fourtonfish** [comment]
Sure, sounds good. Thank you!
