### ISSUE TITLE
No @ mention on JS Twitter

### ISSUE THREAD

**Issue by sarah3585** [fourtonfish/SimpleSharingButtons#5]
Hi,

When using the generator app the JS version doesn't include the @ Twitter handler like the non JS one does (even when both added in their fields of the generator).

**Comment by fourtonfish** [comment]
Hi @sarah3585,

I can't seem to be able to reproduce the issue. Can you give me a bit more detail? What are the exact steps you took?

Thanks!

**Comment by fourtonfish** [comment]
No feedback, closing for now!
