### ISSUE TITLE
Image needs alternative text

### ISSUE THREAD

**Issue by aardrian** [fourtonfish/SimpleSharingButtons#8]
In the output code I see that the `<img>` element has not `alt` attribute. I see that the surrounding `<a href>` has a `title` attribute.

I suggest using the value of the `title` attribute as the value of an `alt` attribute on the `<img>`.

For example, this:

    <li><a href="…" target="_blank" title="Tweet"><img src="images/flat_web_icon_set/color/Twitter.png"></a></li>

Becomes this:

    <li><a href="…" target="_blank" title="Tweet"><img src="images/flat_web_icon_set/color/Twitter.png" alt="Tweet"></a></li>

**Comment by fourtonfish** [comment]
@aardrian Done, thanks for opening the issue!
